capeprivacy/cli

- install.sh
If the connection dies mid-line sh will execute whatever it has read so far. For
example, rm -rf /foo/bar could become rm -rf /.
This is generally considered a "best practice" (for whatever that is worth).
https://web.archive.org/web/20220327083800/https://sandstorm.io/news/2015-09-24-is-curl-bash-insecure-pgp-verified-install
> Wrap the curl installer inside of a function to prevent incomplete execution

- cmd/cape/cmd/run.go
- entities/entities.go
Mostly doing this for tuner, but I think making it an explicit arg that
callers must fully define, rather than having the implementation guess
based on an argument will make things a little more flexible long term
> refactor token parameters in run

- cmd/cape/cmd/deploy.go
- cmd/cape/cmd/run.go
- cmd/cape/cmd/test.go
- cmd/cape/cmd/test_test.go
- sdk/deploy.go
- sdk/run.go
- sdk/test.go
- sdk/test_test.go
- converted CapeTest into the sdk package
- sdk pulls in attest, crypto, entities, and protocol as dependencies from within the repo
- Deploy, Run, and CapeTest sdk functions
- refactored Deploy and Run to take a request object the way CapeTest does
I tried to be thorough in my refactors and merge conflict resolutions, but please review with careful eyes in case something slipped by me! :smiley:
> CAPE-873 | refactor CLI to include go SDK

- cmd/cape/cmd/deploy.go
- cmd/cape/cmd/run.go
- sdk/run.go
`function-hash` option has been marked deprecated with messaging, use `checksum` instead
> Renaming function hash to checksum for clarity of use

- .golangci.yml
- cmd/cape/cmd/run.go
- cmd/cape/cmd/test_test.go
- sdk/test.go
- sdk/test_test.go
Fixes up the grouping for local dependencies, and switches linter config
to use the correct prefix for those dependencies.
> Fixup imports and update linter config

- cmd/cape/cmd/deploy.go
- cmd/cape/cmd/plain_formatter.go
- cmd/cape/cmd/root.go
- go.mod
- go.sum
Adds a flag for selecting an output format. Augments the "plain"
formatter to allow adding fields to a log line which will be converted
to a human-readable key-value pair for output.
For example, a log message "Success! Deployed function to Cape" with
fields "function_id" and "function_checksum" will output:
```
Success! Deployed function to Cape
Function Id ➜ 8fjVmYEXAMPLECdNmq6MCa
Function Checksum ➜ cbca8c9f7ac411381EXAMPLE5a37b1fc09a11dfbc3d44b47
```
Specifying "plain" or omitting the flag will retain the previous
behavior. Specifying "json" will json format the output, and "log" or
"log_plain" will log-format the output with or without optional color
for TTYs, respectively.
> Add optional output formats

- cmd/cape/cmd/deploy.go
- cmd/cape/cmd/root.go
- go.mod
- go.sum
- render/context.go
- render/context_test.go
- render/render.go
- render/render_test.go
Introduces a render package with a Renderer interface for formatting command
output. Provides a JSON renderer, a text-template renderer, and a print
renderer, as well as management for passing a renderer via a context.Context.
The new renderer is configured by the global `-o` flag, replacing it's old
behavior. Logging statements are no longer affected by the flag. Currently,
only the deploy command uses the flag for output.
> Introduce Renderer interface for formatting command output

- cmd/cape/cmd/token.go
This PR is a follow up on https://github.com/capeprivacy/cli/pull/194. It will be rebased once https://github.com/capeprivacy/cli/pull/194 is merged. This PR add the option to render the output as a JSON. It also adds `function_cheksum` an optional argument so the JSON output can hold a function ID, function token and function checksum  which can be used later by SDKs to run a function.
> Add json output to token cmd

- cmd/cape/cmd/list.go
- sdk/deploy.go
- sdk/function_id.go
- sdk/key.go
- sdk/run.go
- sdk/test.go
Sends close message before closing websocket to indicate to the server
that the client is shutting down normally. Also removes uses of
deprecated ioutil.ReadAll which was deprecated in go1.16.
> Close websocket and remove deprecated stdlib calls

- cmd/cape/cmd/run.go
- sdk/deploy.go
- sdk/key.go
- sdk/run.go
Removes the "error reading attestation doc" logs. The failures that
resulted in that log being output could be from things like failing to
download a function, or checksum mismatch, among other things, so this
message was technically accurate but often quite misleading. The actual
error returned from the function is also logged, and this is often much
more helpful in understanding what went wrong.
Also updates the error message when a call to sdk.Run() fails to better
reflect what happened.
> Remove log and update error messages

- cmd/cape/cmd/list.go
Close [CAPE-1071](https://capeprivacy.atlassian.net/browse/CAPE-1071?atlOrigin=eyJpIjoiOGRkZDZiN2I4NTNmNGI3OGIyODk3NTcxNDg4OTJjZmYiLCJwIjoiaiJ9)
This PR add pagination to `cape list`. Currently, without pagination will return all the functions deployed which can be potentially a lot. Pagination can be controlled with a `limit` and `offset` parameter. As a following step to improving the user experience we could potentially look into something like [bubble list](https://github.com/charmbracelet/bubbles#list)
> Add pagination to cape list

- cmd/cape/cmd/list.go
previously, output looked like
```
┌────┬────────────────────┬────────────────────────┬──────────────────────────────────────┐
│  # │ NAME               │ ID                     │ CREATED AT                           │
├────┼────────────────────┼────────────────────────┼──────────────────────────────────────┤
│  0 │ heatmap            │ R4WzjhvTb4AKUerHcXUi3G │ 2022-11-24 00:28:41.11527 +0000 UTC  │
│  1 │ heatmap            │ bcCZgR4gmcQCb2LLCFKAnJ │ 2022-11-24 00:20:51.658571 +0000 UTC │
└────┴────────────────────┴────────────────────────┴──────────────────────────────────────┘
```
I have converted these times to the local timezone, and made them more human readable
```
┌────┬────────────────────┬────────────────────────┬───────────────────┐
│  # │ NAME               │ ID …
```
> improve timezone formatting when listing functions

- cmd/cape/cmd/pcrs.go
- cmd/cape/cmd/run.go
- pcrs/pcrs.go
Adds usage prompts on how to specify PCR verification during run. Also improves error message in case of bad user input. 
Updates get-pcr description since the command takes a while downloading the eif we run. 
Output after change: 
```
Usage:
cape run { <function_id> | <user_name>/<function_name> } [input data] [flags]
Examples:
$ cape run capedocs/echo 'Hello World'
$ echo '1234' | cape run capedocs/echo -f -
$ cape run capedocs/echo 'Hello World' | sed 's/Hello/Hola/'
$ cape run capedocs/echo 5 --pcr=0:placeholderPCR0,8:placeholderPCR8
```
```
cape run 2gmRaLYNGE4gzaMe8s6Wgd  5 --pcr=8:6f1ff0f2a7a0b1c4e02a3a544eb0ff2dffb8b2922b8908d46365c0f0120934092149ec35814c8d944ef1b8fb564b46c7,hi:6f1ff0f2a7a0b1c4e02a3a544eb0ff2dffb8b2922b8908d46365c0f0120934092149ec35814c8d944ef1b8fb564b46c7
error …
```
> Add better description around usage for PCR verification

- crypto/enclave_encrypt.go
Log unknown algorithm for any algorithm that we don't support.
> Add fallthrough clauses to properly log algorithms

- cmd/cape/cmd/list.go
- cmd/cape/cmd/root.go
Improves the output when the list command receives a 401. The error
message no longer references the http status code, and instead
indicates to the user that authentication is required. Also removes
the unhelpful "Command failed with error." message.
> Improve output for unauthorized error

- cmd/cape/cmd/root.go
- cmd/cape/cmd/version.go
- go.mod
- go.sum
- sdk/encrypt.go
It looks like this ...
```
cape deploy isprime
Deploying function to Cape ...
Function ID       ➜  iaHGcKFr532kkZmUmAyFQt
Function Checksum ➜  66731e5ccf226680dd5c98a1d1ad52b7a4c986984042d0672d8f3153130b34a8
Function Name     ➜  bendecoste/isprime 
There is a new version (v0.4.4) of the Cape CLI available, you can download it at https://github.com/capeprivacy/cli/releases/latest
Or upgrade by running 
curl -fsSL https://raw.githubusercontent.com/capeprivacy/cli/main/install.sh | sh
```
> check to see if there is a new version of cli

- cmd/cape/cmd/login.go
- cmd/cape/cmd/token.go
- cmd/cape/cmd/token_test.go
This PR does the following ... 
- Make the function ID optional. This is consistent with the UI right now.
- Remove the extra text when creating a token, so that `cape token create` will just print `<token>` rather than `Success! Your token is <token>`.
- Remove the command for function tokens, it is confusing when used in conjunction with PATs, and you can get their behavior with the --function flag
- Add examples to the token create command
> Token Tweaks

- cmd/cape/cmd/encrypt.go
- cmd/cape/cmd/encrypt_test.go
CAPE-1385 
You can cape encrypt nothing because the error check conditions were wrong.
> fix encrypt input error check

- sdk/test.go
When connecting to an enclave to process a request, for example to run a
function, the API may redirect to a specific enclave pool URL. This
redirect is normal behavior, and is an implementation detail. The
previous logs which referenced the redirect explicitly were not helpful
to an end-user. This change removes references to that redirect code to
make the messages more meaningful to a typical end-user.
> Improve logging and error message connecting to enclave

- cmd/cape/cmd/test.go
- cmd/cape/cmd/test_test.go
- go.mod
- go.sum
- mocks/mocks.go
- sdk/deploy.go
- sdk/encrypt.go
- sdk/key.go
- sdk/run.go
- sdk/test.go
- sdk/test_test.go
We do this by updating to the latest attest package which let's us override the current time during verifying a certificate chain. We read the NotBefore value from the attestation document Certificate and update the current time to be NotBefore. If we don't do this then the certificate chain verification will fail because the Attestation document is only valid for 4 hours.
> Renable cert chain validation when calling key

- cmd/cape/cmd/deploy.go
- cmd/cape/cmd/run.go
- cmd/cape/cmd/token.go
- entities/entities.go
- protocol/protocol.go
- sdk/deploy.go
- sdk/key.go
- sdk/run.go
- sdk/test_test.go
Looking at the Prometheus metric `function_token_authorization` function tokens are no longer being used.
> Removing function token support

- .github/workflows/release.yml
Switches the goreleaser workflow to use a secret configured on the
repository instead of the token generated by GitHub for the action
invocation. This is necessary in order to grant access to the homebrew
repository.
> Use configured repo secret instead of default action token

- .github/workflows/main.yml
- .github/workflows/release.yml
- cmd/cape/cmd/deploy.go
- cmd/cape/cmd/test.go
- cmd/cape/cmd/test_test.go
- sdk/deploy.go
refactor test to support zip input, this is so that we can re-use the zip file in our own internal tests.
> support zip input for test

- cmd/cape/cmd/config.go
- cmd/cape/cmd/config_test.go
- cmd/cape/cmd/root.go
Currently the --config flag available on the root command takes in a file name where the file must exist within the default configuration directory. The contents can then be used to set configuration parameters.
However it is much more common for a cli to take a full config file path where the file can then specify items _such as_ the configuration directory. We use this directory to store auth, key, and token information and forcing the creation of `~/.config/cape` in an environment to host a config override file that specifies a different location is an anti-pattern. 
In this change the `cape cmd --config file` allows for any fully qualified file path to be passed and used to set up a one to all of the configuration values, defaulting to the environment variables, and then hardcoded …
> Change --config flag from file name to file
